import {
  LayoutDashboard,
  Users,
  Shield,
  UserCog,
  Monitor,
  KeyRound,
  Activity,
  UserPlus,
  Building2,
  Briefcase,
  MapPin,
  Network,
  Clock,
  Calendar,
  CheckCircle2,
  Settings,
  Package,
  Truck,
  Warehouse,
  Book,
  ShoppingCart,
} from 'lucide-react';
import { MenuItem } from './sidebar.types';

export const CUSTOMER_PORTAL_MENU_ITEMS: MenuItem[] = [
  {
    label: 'Dashboard',
    href: '/system/dashboard',
    icon: LayoutDashboard,
    description: 'Overview of your account activity',
    menu_code: 'CP-01',
  },
  {
    label: 'User Management',
    icon: UserCog,
    description: 'Manage users and roles',
    menu_code: 'CP-02',
    children: [
      {
        label: 'Users',
        href: '/system/users',
        icon: Users,
        description: 'Manage tenant users',
        menu_code: 'CP-02-01',
        permission: 'system.user.view',
      },
      {
        label: 'Roles',
        href: '/system/roles',
        icon: Shield,
        description: 'Manage user roles and permissions',
        menu_code: 'CP-02-02',
        permission: 'system.role.view',
      },
      {
        label: 'Active Sessions',
        href: '/system/sessions',
        icon: KeyRound,
        description: 'View and manage all active sessions',
        menu_code: 'CP-02-03',
        permission: 'system.session.view',
      },
    ],
  },
  {
    label: 'My Sessions',
    href: '/system/my-sessions',
    icon: Monitor,
    description: 'View and manage your active sessions',
    menu_code: 'CP-03',
  },
  {
    label: 'Organization',
    icon: Network,
    description: 'Manage company structure',
    menu_code: 'CP-04',
    children: [
      {
        label: 'Departments',
        href: '/hris/departments',
        icon: Building2,
        description: 'Manage organizational departments',
        menu_code: 'CP-04-01',
        permission: 'hris.department.view',
      },
      {
        label: 'Designations',
        href: '/hris/designations',
        icon: Briefcase,
        description: 'Manage job titles and ranks',
        menu_code: 'CP-04-02',
        permission: 'hris.designation.view',
      },
      {
        label: 'Branches',
        href: '/hris/branches',
        icon: MapPin,
        description: 'Manage physical or logical locations',
        menu_code: 'CP-04-03',
        permission: 'hris.branch.view',
      },
      {
        label: 'Employees',
        icon: Users,
        description: 'Manage organization staff and user accounts',
        menu_code: 'CP-04-04',
        permission: 'hris.employee.view',
        children: [
          {
            label: 'Employee List',
            href: '/hris/employees',
            icon: Users,
            description: 'View and manage employees',
            menu_code: 'CP-04-04-01',
            permission: 'hris.employee.view',
          },
          {
            label: 'Employee Onboarding',
            href: '/hris/employees/onboarding',
            icon: UserPlus,
            description: 'Add a new employee with guided setup',
            menu_code: 'CP-04-04-02',
            permission: 'hris.employee.manage',
          },
        ],
      },
    ],
  },
  {
    label: 'HR Management',
    icon: Briefcase,
    description: 'Attendance and Leave Management',
    menu_code: 'CP-05',
    children: [
      {
        label: 'Overview',
        href: '/hris',
        icon: LayoutDashboard,
        description: 'HRIS summary and quick actions',
        menu_code: 'CP-05-01',
      },
      {
        label: 'Attendance',
        href: '/hris/attendance',
        icon: Clock,
        description: 'Daily time logs and clock-in',
        menu_code: 'CP-05-02',
        permission: 'hris.attendance.log',
      },
      {
        label: 'Timesheets',
        href: '/hris/timesheets',
        icon: LayoutDashboard,
        description: 'Aggregate logs and review hours',
        menu_code: 'CP-05-03',
        permission: 'hris.timesheet.view',
      },
      {
        label: 'Pay Periods',
        href: '/hris/pay-periods',
        icon: Calendar,
        description: 'Manage payroll cycles',
        menu_code: 'CP-05-04',
        permission: 'hris.payroll.view',
      },
      {
        label: 'My Leaves',
        href: '/hris/my-leaves',
        icon: Calendar,
        description: 'Apply for and track leaves',
        menu_code: 'CP-05-05',
        permission: 'hris.leave.request',
      },
      {
        label: 'Leave Approval',
        href: '/hris/leave-requests',
        icon: CheckCircle2,
        description: 'Review leave applications',
        menu_code: 'CP-05-06',
        permission: 'hris.leave.manage',
      },
      {
        label: 'Leave Types',
        href: '/hris/leave-types',
        icon: Settings,
        description: 'Configure leave policies',
        menu_code: 'CP-05-07',
        permission: 'hris.leave_type.manage',
      },
      {
        label: 'Job Status',
        href: '/hris/timesheets/job-status',
        icon: Activity,
        description: 'View automated processing status',
        menu_code: 'CP-05-08',
        permission: 'hris.timesheet.view',
      },
    ],
  },
  {
    label: 'Operations',
    icon: Settings,
    menu_code: 'OPS',
    permission: 'operations.view',
    children: [
      {
        label: 'Warehouses',
        href: '/operations/warehouses',
        icon: Warehouse,
        menu_code: 'CP-06-01',
        permission: 'operations.warehouses.view',
      },
      {
        label: 'Stock Ledger',
        href: '/operations/stock-ledger',
        icon: Book,
        menu_code: 'CP-06-02',
        permission: 'operations.stock-ledger.view',
      },
      {
        label: 'Materials',
        href: '/operations/materials',
        icon: Package,
        menu_code: 'CP-06-03',
        permission: 'operations.materials.view',
      },
      {
        label: 'Sales Orders',
        href: '/operations/sales-orders',
        icon: ShoppingCart,
        menu_code: 'CP-06-04',
        permission: 'operations.sales-order.view',
      },
      {
        label: 'Goods Receipts',
        href: '/operations/goods-receipts',
        icon: Package,
        menu_code: 'CP-06-05',
        permission: 'operations.goods-receipt.view',
      },
    ],
  },
];
