import { FormField } from "@/components/entity-manager";

export const formFields: FormField[] = [
  {
    name: "firstName",
    label: "First Name",
    type: "text",
    required: true,
    placeholder: "e.g. John",
    width: "half",
  },
  {
    name: "lastName",
    label: "Last Name",
    type: "text",
    required: true,
    placeholder: "e.g. Doe",
    width: "half",
  },
  {
    name: "email",
    label: "Email Address",
    type: "email",
    required: true,
    placeholder: "e.g. john.doe@company.com",
    width: "full",
  },
  {
    name: "password",
    label: "Password",
    type: "text",
    required: true,
    placeholder: "Default: password123",
    width: "full",
    disabled: true,
    defaultValue: "password123",
    description: "Default password is set to 'password123'",
  },
  {
    name: "roleIds",
    label: "Role", 
    type: "select", 
    required: true,
    placeholder: "ADMIN",
    width: "full",
    defaultValue: "ADMIN",
    options: [{ label: "Admin", value: "ADMIN" }],
  },
  {
    name: "status",
    label: "Status",
    type: "select",
    required: true,
    options: [
      { label: "Active", value: "ACTIVE" },
      { label: "Inactive", value: "INACTIVE" },
      { label: "Banned", value: "BANNED" },
    ],
    defaultValue: "ACTIVE",
  },
];
