export const inventory_seeder = [
  {
    module: 'INVENTORY',
    resource: 'ADJUSTMENT',
    action: 'CREATE',
    slug: 'inventory.adjustment.create',
    name: 'Create Stock Adjustments',
  },
  {
    module: 'INVENTORY',
    resource: 'ADJUSTMENT',
    action: 'READ',
    slug: 'inventory.adjustment.read',
    name: 'Read Stock Adjustments',
  },
  {
    module: 'INVENTORY',
    resource: 'ADJUSTMENT',
    action: 'EDIT',
    slug: 'inventory.adjustment.edit',
    name: 'Edit Stock Adjustments',
  },
  {
    module: 'INVENTORY',
    resource: 'ADJUSTMENT',
    action: 'APPROVE',
    slug: 'inventory.adjustment.approve',
    name: 'Approve Stock Adjustments',
  },
  {
    module: 'INVENTORY',
    resource: 'ADJUSTMENT',
    action: 'CANCEL',
    slug: 'inventory.adjustment.cancel',
    name: 'Cancel Stock Adjustments',
  },
  {
    module: 'INVENTORY',
    resource: 'ADJUSTMENT',
    action: 'DELETE',
    slug: 'inventory.adjustment.delete',
    name: 'Delete Stock Adjustments',
  },
  // Inventory - Stock Transfers
  {
    module: 'INVENTORY',
    resource: 'TRANSFER',
    action: 'CREATE',
    slug: 'inventory.transfer.create',
    name: 'Create Stock Transfers',
  },
  {
    module: 'INVENTORY',
    resource: 'TRANSFER',
    action: 'READ',
    slug: 'inventory.transfer.read',
    name: 'Read Stock Transfers',
  },
  {
    module: 'INVENTORY',
    resource: 'TRANSFER',
    action: 'EDIT',
    slug: 'inventory.transfer.edit',
    name: 'Edit Stock Transfers',
  },
  {
    module: 'INVENTORY',
    resource: 'TRANSFER',
    action: 'APPROVE',
    slug: 'inventory.transfer.approve',
    name: 'Approve Stock Transfers',
  },
  {
    module: 'INVENTORY',
    resource: 'TRANSFER',
    action: 'SHIP',
    slug: 'inventory.transfer.ship',
    name: 'Ship Stock Transfers',
  },
  {
    module: 'INVENTORY',
    resource: 'TRANSFER',
    action: 'RECEIVE',
    slug: 'inventory.transfer.receive',
    name: 'Receive Stock Transfers',
  },
  {
    module: 'INVENTORY',
    resource: 'TRANSFER',
    action: 'CANCEL',
    slug: 'inventory.transfer.cancel',
    name: 'Cancel Stock Transfers',
  },
  {
    module: 'INVENTORY',
    resource: 'TRANSFER',
    action: 'DELETE',
    slug: 'inventory.transfer.delete',
    name: 'Delete Stock Transfers',
  },
];
