export const operations_seeder = [
  {
    module: 'operations',
    resource: 'item',
    action: 'view',
    slug: 'operations.item.view',
    name: 'View Items',
  },
  {
    module: 'operations',
    resource: 'item',
    action: 'manage',
    slug: 'operations.item.manage',
    name: 'Manage Items',
  },
  // Operations - Materials
  {
    module: 'operations',
    resource: 'materials',
    action: 'view',
    slug: 'operations.materials.view',
    name: 'View Materials',
  },
  {
    module: 'operations',
    resource: 'materials',
    action: 'create',
    slug: 'operations.materials.create',
    name: 'Create Materials',
  },
  {
    module: 'operations',
    resource: 'materials',
    action: 'update',
    slug: 'operations.materials.update',
    name: 'Update Materials',
  },
  {
    module: 'operations',
    resource: 'materials',
    action: 'delete',
    slug: 'operations.materials.delete',
    name: 'Delete Materials',
  },
  {
    module: 'operations',
    resource: 'materials',
    action: 'manage',
    slug: 'operations.materials.manage',
    name: 'Manage Materials',
  },
  {
    module: 'operations',
    resource: 'materials',
    action: 'import',
    slug: 'operations.materials.import',
    name: 'Import Materials',
  },
  {
    module: 'operations',
    resource: 'materials',
    action: 'export',
    slug: 'operations.materials.export',
    name: 'Export Materials',
  },
  {
    module: 'operations',
    resource: 'category',
    action: 'manage',
    slug: 'operations.category.manage',
    name: 'Manage Item Categories',
  },
  {
    module: 'operations',
    resource: 'uom',
    action: 'manage',
    slug: 'operations.uom.manage',
    name: 'Manage Units of Measure',
  },
  // Operations - Warehouses & Stock
  {
    module: 'operations',
    resource: 'warehouse',
    action: 'manage',
    slug: 'operations.warehouse.manage',
    name: 'Manage Warehouses & Locations',
  },
  {
    module: 'operations',
    resource: 'stock',
    action: 'manage',
    slug: 'operations.stock.manage',
    name: 'Manage Stock Movements',
  },
  {
    module: 'operations',
    resource: 'bom',
    action: 'view',
    slug: 'operations.bom.view',
    name: 'View Bill of Materials',
  },
  {
    module: 'operations',
    resource: 'bom',
    action: 'manage',
    slug: 'operations.bom.manage',
    name: 'Manage Bill of Materials',
  },
  {
    module: 'operations',
    resource: 'dashboard',
    action: 'view',
    slug: 'operations.dashboard.view',
    name: 'View Operations Dashboard',
  },
  {
    module: 'operations',
    resource: 'bom_costing',
    action: 'view',
    slug: 'operations.bom_costing.view',
    name: 'View BOM Costings',
  },
  {
    module: 'operations',
    resource: 'bom_costing',
    action: 'manage',
    slug: 'operations.bom_costing.manage',
    name: 'Manage BOM Costings',
  },
  {
    module: 'operations',
    resource: 'bom_costing_history',
    action: 'view',
    slug: 'operations.bom_costing_history.view',
    name: 'View BOM Costing History',
  },
  {
    module: 'operations',
    resource: 'bom_costing',
    action: 'calculate',
    slug: 'operations.bom_costing.calculate',
    name: 'Calculate BOM Costings',
  },
  {
    module: 'operations',
    resource: 'stock',
    action: 'view',
    slug: 'operations.stock.view',
    name: 'View Stock Ledger',
  },
  // Operations - Goods Receipt
  {
    module: 'operations',
    resource: 'goods-receipt',
    action: 'create',
    slug: 'operations.goods-receipt.create',
    name: 'Create Goods Receipt',
  },
  {
    module: 'operations',
    resource: 'goods-receipt',
    action: 'view',
    slug: 'operations.goods-receipt.view',
    name: 'View Goods Receipt',
  },
  {
    module: 'operations',
    resource: 'goods-receipt',
    action: 'update',
    slug: 'operations.goods-receipt.update',
    name: 'Update Goods Receipt',
  },
  {
    module: 'operations',
    resource: 'goods-receipt',
    action: 'confirm',
    slug: 'operations.goods-receipt.confirm',
    name: 'Confirm Goods Receipt',
  },
  {
    module: 'operations',
    resource: 'goods-receipt',
    action: 'cancel',
    slug: 'operations.goods-receipt.cancel',
    name: 'Cancel Goods Receipt',
  },
  {
    module: 'operations',
    resource: 'goods-receipt',
    action: 'delete',
    slug: 'operations.goods-receipt.delete',
    name: 'Delete Goods Receipt',
  },
  // Operations - Production
  {
    module: 'operations',
    resource: 'production',
    action: 'view',
    slug: 'operations.production.view',
    name: 'View Production Batches',
  },
  {
    module: 'operations',
    resource: 'production',
    action: 'create',
    slug: 'operations.production.create',
    name: 'Create Production Batch',
  },
  {
    module: 'operations',
    resource: 'production',
    action: 'update',
    slug: 'operations.production.update',
    name: 'Update Production Batch',
  },
  {
    module: 'operations',
    resource: 'production',
    action: 'start',
    slug: 'operations.production.start',
    name: 'Start Production Batch',
  },
  {
    module: 'operations',
    resource: 'production',
    action: 'complete',
    slug: 'operations.production.complete',
    name: 'Complete Production Batch',
  },
  {
    module: 'operations',
    resource: 'production',
    action: 'cancel',
    slug: 'operations.production.cancel',
    name: 'Cancel Production Batch',
  },
  {
    module: 'operations',
    resource: 'production',
    action: 'delete',
    slug: 'operations.production.delete',
    name: 'Delete Production Batch',
  },
  // Operations - Goods Issuance
  {
    module: 'operations',
    resource: 'goods-issuance',
    action: 'create',
    slug: 'goods-issuance.create',
    name: 'Create Goods Issuance',
  },
  {
    module: 'operations',
    resource: 'goods-issuance',
    action: 'view',
    slug: 'goods-issuance.view',
    name: 'View Goods Issuance',
  },
  {
    module: 'operations',
    resource: 'goods-issuance',
    action: 'update',
    slug: 'goods-issuance.update',
    name: 'Update Goods Issuance',
  },
  {
    module: 'operations',
    resource: 'goods-issuance',
    action: 'approve',
    slug: 'goods-issuance.approve',
    name: 'Approve Goods Issuance',
  },
  {
    module: 'operations',
    resource: 'goods-issuance',
    action: 'cancel',
    slug: 'goods-issuance.cancel',
    name: 'Cancel Goods Issuance',
  },
  {
    module: 'operations',
    resource: 'goods-issuance',
    action: 'delete',
    slug: 'goods-issuance.delete',
    name: 'Delete Goods Issuance',
  },

  {
    module: 'operations',
    resource: 'sales-order',
    action: 'create',
    slug: 'operations.sales-order.create',
    name: 'Create Sales Orders',
  },
  {
    module: 'operations',
    resource: 'sales-order',
    action: 'view',
    slug: 'operations.sales-order.view',
    name: 'View Sales Orders',
  },
  {
    module: 'operations',
    resource: 'sales-order',
    action: 'update',
    slug: 'operations.sales-order.update',
    name: 'Update Sales Orders',
  },
  {
    module: 'operations',
    resource: 'sales-order',
    action: 'delete',
    slug: 'operations.sales-order.delete',
    name: 'Delete Sales Orders',
  },
  {
    module: 'operations',
    resource: 'sales-order',
    action: 'confirm',
    slug: 'operations.sales-order.confirm',
    name: 'Confirm Sales Orders',
  },
  {
    module: 'operations',
    resource: 'sales-order',
    action: 'ship',
    slug: 'operations.sales-order.ship',
    name: 'Ship Sales Orders',
  },
  {
    module: 'operations',
    resource: 'sales-order',
    action: 'deliver',
    slug: 'operations.sales-order.deliver',
    name: 'Deliver Sales Orders',
  },
  {
    module: 'operations',
    resource: 'sales-order',
    action: 'cancel',
    slug: 'operations.sales-order.cancel',
    name: 'Cancel Sales Orders',
  },
];
