### Create Item Category
POST {{API_BASE_URL}}/v1/ops/item-categories
Content-Type: application/json

{
  "code": "FAB",
  "name": "Fabric Rolls",
  "description": "Greige and dyed fabrics"
}

### List Item Categories
GET {{API_BASE_URL}}/v1/ops/item-categories


### Update Item Category
PATCH {{API_BASE_URL}}/v1/ops/item-categories/1
Content-Type: application/json

{
  "name": "Premium Fabric Rolls",
  "description": "Updated description"
}

### Create Unit of Measure
POST {{API_BASE_URL}}/v1/ops/item-uoms
Content-Type: application/json

{
  "code": "MTR",
  "name": "Meter",
  "precision": 2
}

### List Units of Measure
GET {{API_BASE_URL}}/v1/ops/item-uoms


### Update Unit of Measure
PATCH {{API_BASE_URL}}/v1/ops/item-uoms/1
Content-Type: application/json

{
  "name": "Meter (m)",
  "precision": 3
}

### Create Item
POST {{API_BASE_URL}}/v1/ops/items
Content-Type: application/json

{
  "code": "TSHIRT-WHT-001",
  "name": "Basic White Tee",
  "description": "Crew neck, 180gsm cotton",
  "categoryId": 1,
  "baseUomId": 1,
  "isActive": true
}

### List Items
GET {{API_BASE_URL}}/v1/ops/items


### Update Item
PATCH {{API_BASE_URL}}/v1/ops/items/1
Content-Type: application/json

{
  "description": "Updated fabric blend",
  "isActive": true
}
