### Admin Login (establish session cookie)
# @name adminLogin
POST {{API_BASE_URL}}/v1/auth/login
Content-Type: application/json

{
  "email": "{{TEST_USERNAME}}",
  "password": "{{TEST_USER_PASSWORD}}"
}


 
### Get Profile (Me)
GET {{API_BASE_URL}}/v1/auth/me
Content-Type: application/json

### Logout
POST {{API_BASE_URL}}/v1/auth/logout
Content-Type: application/json
