import { FormField } from '@/components/entity-manager';
import { MaterialType } from '@/store/api/materialsApi';

export const formFields: FormField[] = [
  {
    name: 'sku',
    label: 'SKU',
    type: 'text',
    placeholder: 'Enter SKU (e.g., RAW-001)',
    required: true,
    description: 'Unique stock keeping unit for this material',
  },
  {
    name: 'name',
    label: 'Material Name',
    type: 'text',
    placeholder: 'Enter material name',
    required: true,
    description: 'Descriptive name for the material',
  },
  {
    name: 'description',
    label: 'Description',
    type: 'textarea',
    placeholder: 'Enter material description (optional)',
    description: 'Additional details about the material',
    width: 'full',
  },
  {
    name: 'materialType',
    label: 'Material Type',
    type: 'select',
    placeholder: 'Select material type',
    required: true,
    options: [
      { label: 'Raw Material', value: MaterialType.RAW },
      { label: 'Semi-Finished', value: MaterialType.SEMI_FINISHED },
      { label: 'Finished Goods', value: MaterialType.FINISHED },
      { label: 'Service', value: MaterialType.SERVICE },
    ],
    defaultValue: MaterialType.RAW,
    description: 'Classification of the material',
  },
  {
    name: 'materialGroup',
    label: 'Material Group',
    type: 'text',
    placeholder: 'Enter material group (e.g., METALS, FABRICS)',
    description: 'Group for organizing similar materials',
  },
  {
    name: 'baseUom',
    label: 'Base Unit of Measure',
    type: 'select',
    placeholder: 'Select UoM',
    required: true,
    options: [
      { label: 'Each (EA)', value: 'EA' },
      { label: 'Kilogram (KG)', value: 'KG' },
      { label: 'Gram (G)', value: 'G' },
      { label: 'Meter (M)', value: 'M' },
      { label: 'Centimeter (CM)', value: 'CM' },
      { label: 'Liter (L)', value: 'L' },
      { label: 'Milliliter (ML)', value: 'ML' },
      { label: 'Square Meter (SQM)', value: 'SQM' },
      { label: 'Cubic Meter (CBM)', value: 'CBM' },
      { label: 'Ton (TON)', value: 'TON' },
      { label: 'Piece (PCS)', value: 'PCS' },
      { label: 'Box (BOX)', value: 'BOX' },
      { label: 'Roll (ROLL)', value: 'ROLL' },
      { label: 'Bag (BAG)', value: 'BAG' },
    ],
    description: 'Primary unit of measure for this material',
  },
  {
    name: 'netWeight',
    label: 'Net Weight',
    type: 'number',
    placeholder: 'Enter net weight',
    description: 'Net weight of the material',
    valueType: 'number',
  },
  {
    name: 'weightUom',
    label: 'Weight UoM',
    type: 'select',
    placeholder: 'Select weight unit',
    options: [
      { label: 'Kilogram (KG)', value: 'KG' },
      { label: 'Gram (G)', value: 'G' },
      { label: 'Ton (TON)', value: 'TON' },
      { label: 'Pound (LB)', value: 'LB' },
      { label: 'Ounce (OZ)', value: 'OZ' },
    ],
    defaultValue: 'KG',
    description: 'Unit of measure for weight',
  },
  {
    name: 'isActive',
    label: 'Active Status',
    type: 'select',
    placeholder: 'Select status',
    options: [
      { label: 'Active', value: 'true' },
      { label: 'Inactive', value: 'false' },
    ],
    defaultValue: 'true',
    description: 'Whether this material is active for use',
    valueType: 'boolean',
  },
];
